### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Love-Kogasa** [BIYUEHU/huliws#1]
U project is really cool.  
But I try run my script with module on Termux find some err.  
On example run
```bash
file:///storage/emulated/0/Js/mcwss/E.js:4
const mcwss = new Mcwss({ port: 2333 });
              ^

TypeError: Mcwss is not a constructor
    at file:///storage/emulated/0/Js/mcwss/E.js:4:15       at ModuleJob.run (node:internal/modules/esm/module_job:218:25)                                                at async ModuleLoader.import 
(node:internal/modules/esm/loader:323:24)                                        at async loadESM
 (node:internal/process/esm_loader:28:7)                                                      at async handleMainPromise
 (node:internal/modules/run_main:120:12)                                        
Node.js v21.6.2
```
Look like u want export default as Mcwss and export Mcwss on module object.  
u can try  
```js
Mcwss.Mcwss = Mcwss
module.exports = Mcwss
```
Besides, there is another question
On `wss.start()` it success to emit event "ready".  
But cant open ws server.  
My test.js
```js
const { Mcwss } = require( "mcwss" )
const rl = require( "readline-sync" )
const wss = new Mcwss({ port : 8080 })
wss.on( "ready", () => console.log( "ws://localhost:8080" ) )
wss.on( "player_message", function( event ){
    event.client.chat( "hello " + enent.sender )
})
wss.start()
rl.question( "put some key to close" ) && wss.stop()
```
Sorry to bother you.  
have a good breakfast!

**Comment by biyuehu** [comment]
For first question,u can try to use `ESM` or TypeScript:

```js
import Mcwss from "mcwss"

const  wss = new Mcwss({ server: 2333 })
```

There are indeed problems at `CommandJs`,and because I use typescript to develop.I dont know if it's TSC building problem or another problems.

For second:

I'm so sorry that I didn't update `README.md` in time.After `v2.1.0` the wss configurations changed:

```js
const  wss = new Mcwss({ server: 2333 })
```

`server` was received a number or `WebSocket.Server` instance,it's for better implementing ws and htttp server used the same port.

And if your server wasn't started or the program exited,it may occur error (such as the port is occupied),you should handle error and it's necessary:

```js
wss.on('close', ({raw}) => console.log('closed', raw))
wss.on('error', ({client, error}) => console.log(`Error:`, client, error))
```

Your code had problems about `player_message` event,it expects `event.body.sender` instead of `enent.sender`,and you should judge `event.body.type`,overwise it will keep call `event.client.chat()`,full example:

```js
// @ts-check

const { Mcwss } = require("mcwss");
const rl = require( "readline-sync" )
const wss = new Mcwss({ server: 8080 });
wss.on("ready", () => console.log("ws://localhost:8080"));
wss.on("close", ({ raw }) => console.log("closed", raw));
wss.on("error", ({ client, error }) => console.log(`Error:`, client, error));
wss.on("player_message", function (event) {
  if (event.body.type === 'chat') event.client.chat("hello " + event.body.sender);
});
wss.start();
rl.question( "put some key to close" ) && wss.stop()
```

If your editor supports u can add comment `@ts-check` at the code top,it will have a better data type prompt.About more details with minecraft bedorck websocket data type please refer to [Minecraft Wiki](https://zh.minecraft.wiki/w/Tutorial:WebSocket).
